# fly.toml app configuration file for TCP relay server

app = "relayserver-7mrprq"
primary_region = "gig"

[env]
PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
